path fix. scripts install now but fail
I think because installed binary gdal is 3.4.2 and repo tree is 3.5.
Note 'import errror' for _gdal.cpython-38-x86_64-linux-gnu.so

```
gitpod /workspace/gdal/swig/python (py-conscripts) $ python gdal-utils/osgeo_utils/gdal_edit.py
Traceback (most recent call last):
  File "/home/gitpod/.pyenv/versions/3.8.12/lib/python3.8/site-packages/osgeo/__init__.py", line 29, in swig_import_helper
    return importlib.import_module(mname)
  File "/home/gitpod/.pyenv/versions/3.8.12/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1166, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/gitpod/.pyenv/versions/3.8.12/lib/python3.8/site-packages/osgeo/_gdal.cpython-38-x86_64-linux-gnu.so: undefined symbol: VSIClearCredentials

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gdal-utils/osgeo_utils/gdal_edit.py", line 33, in <module>
    from osgeo import gdal
  File "/home/gitpod/.pyenv/versions/3.8.12/lib/python3.8/site-packages/osgeo/__init__.py", line 45, in <module>
    _gdal = swig_import_helper()
  File "/home/gitpod/.pyenv/versions/3.8.12/lib/python3.8/site-packages/osgeo/__init__.py", line 42, in swig_import_helper
    return importlib.import_module('_gdal')
  File "/home/gitpod/.pyenv/versions/3.8.12/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_gdal'
```